language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  exclude:

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - travis_retry composer update --no-interaction --prefer-source
  - if [ "$LARAVEL_VERSION" != "" ]; then composer require --dev "laravel/laravel:${LARAVEL_VERSION}" --no-update; fi;

script:
  - vendor/bin/phpunit

env:
  - LARAVEL_VERSION=6.*
